In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [7]:
import pandas as pd

train_df = pd.read_csv(
    "/kaggle/input/datasets/organizations/zalando-research/fashionmnist/fashion-mnist_train.csv"
)

test_df = pd.read_csv(
    "/kaggle/input/datasets/organizations/zalando-research/fashionmnist/fashion-mnist_test.csv"
)

print(train_df.shape)
print(test_df.shape)

(60000, 785)
(10000, 785)

In [8]:
X_train = train_df.drop('label', axis=1)
y_train = train_df['label']

X_test = test_df.drop('label', axis=1)
y_test = test_df['label']

print(X_train.shape)
print(y_train.shape)

(60000, 784)
(60000,)

In [9]:
X_train = X_train / 255.0
X_test = X_test / 255.0

print(X_train.min().min(), X_train.max().max())

0.0 1.0

In [10]:
# MODEL:1 ANN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 109,386 (427.29 KB)

 Trainable params: 109,386 (427.29 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train,
    epochs=5,
    validation_split=0.2,
    batch_size=32
)

Epoch 1/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8148 - loss: 0.5163 - val_accuracy: 0.8597 - val_loss: 0.3993
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8617 - loss: 0.3803 - val_accuracy: 0.8571 - val_loss: 0.3932
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8741 - loss: 0.3447 - val_accuracy: 0.8737 - val_loss: 0.3513
Epoch 4/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8836 - loss: 0.3175 - val_accuracy: 0.8690 - val_loss: 0.3644
Epoch 5/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8889 - loss: 0.2981 - val_accuracy: 0.8732 - val_loss: 0.3538

In [12]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8695 - loss: 0.3428
Test Accuracy: 0.8694999814033508

In [13]:
# MODEL 2: DEEP ANN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model2 = Sequential([
    Dense(256, activation='relu', input_shape=(784,)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(10, activation='softmax')
])

model2.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 256)            │       200,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 10)             │           330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 244,522 (955.16 KB)

 Trainable params: 244,522 (955.16 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
# MODEL TRAINING
model2.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history2 = model2.fit(
    X_train,
    y_train,
    epochs=5,
    validation_split=0.2,
    batch_size=32
)

Epoch 1/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8065 - loss: 0.5328 - val_accuracy: 0.8331 - val_loss: 0.4433
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8593 - loss: 0.3831 - val_accuracy: 0.8496 - val_loss: 0.4188
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8728 - loss: 0.3478 - val_accuracy: 0.8660 - val_loss: 0.3584
Epoch 4/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8796 - loss: 0.3247 - val_accuracy: 0.8733 - val_loss: 0.3538
Epoch 5/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8878 - loss: 0.3027 - val_accuracy: 0.8719 - val_loss: 0.3571

In [15]:
loss2, accuracy2 = model2.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy2)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8689 - loss: 0.3557
Test Accuracy: 0.8689000010490417

In [16]:
# MODEL 3: CNN

print(X_train.shape)

(60000, 784)

In [17]:
X_train_cnn = X_train.values.reshape(-1, 28, 28, 1)
X_test_cnn = X_test.values.reshape(-1, 28, 28, 1)

print(X_train_cnn.shape)
print(X_test_cnn.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

cnn_model = Sequential([

    Conv2D(32, (3,3), activation='relu',
           input_shape=(28,28,1)),

    MaxPooling2D((2,2)),

    Conv2D(64, (3,3), activation='relu'),

    MaxPooling2D((2,2)),

    Flatten(),

    Dense(128, activation='relu'),

    Dense(10, activation='softmax')
])

cnn_model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 11, 11, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 5, 5, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 1600)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 128)            │       204,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 225,034 (879.04 KB)

 Trainable params: 225,034 (879.04 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
# MODEL TRAINING

cnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_cnn = cnn_model.fit(
    X_train_cnn,
    y_train,
    epochs=5,
    validation_split=0.2,
    batch_size=32
)

Epoch 1/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 22s 14ms/step - accuracy: 0.8259 - loss: 0.4771 - val_accuracy: 0.8692 - val_loss: 0.3617
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 21s 14ms/step - accuracy: 0.8818 - loss: 0.3250 - val_accuracy: 0.8929 - val_loss: 0.3032
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 21s 14ms/step - accuracy: 0.8986 - loss: 0.2760 - val_accuracy: 0.8988 - val_loss: 0.2893
Epoch 4/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 20s 14ms/step - accuracy: 0.9105 - loss: 0.2418 - val_accuracy: 0.9000 - val_loss: 0.2779
Epoch 5/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 20s 13ms/step - accuracy: 0.9200 - loss: 0.2141 - val_accuracy: 0.9088 - val_loss: 0.2568

In [20]:
loss_cnn, accuracy_cnn = cnn_model.evaluate(
    X_test_cnn,
    y_test
)

print("CNN Test Accuracy:", accuracy_cnn)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9110 - loss: 0.2428
CNN Test Accuracy: 0.9110000133514404

In [1]:
# TEXT DATASET

import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    print(dirname)
    for f in filenames[:10]:
        print("   ", f)

/kaggle/input
/kaggle/input/notebooks
/kaggle/input/notebooks/pavansanagapati
/kaggle/input/notebooks/pavansanagapati/a-simple-cnn-model-beginner-guide
    __results__.html
    __notebook__.ipynb
    __output__.json
    custom.css
/kaggle/input/notebooks/pavansanagapati/a-simple-cnn-model-beginner-guide/__results___files
    __results___39_0.png
    __results___35_0.png
    __results___16_0.png
    __results___30_1.png
    __results___18_0.png
    __results___35_1.png
/kaggle/input/datasets
/kaggle/input/datasets/lakshmi25npathi
/kaggle/input/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
    IMDB Dataset.csv
/kaggle/input/datasets/organizations
/kaggle/input/datasets/organizations/zalando-research
/kaggle/input/datasets/organizations/zalando-research/fashionmnist
    t10k-labels-idx1-ubyte
    t10k-images-idx3-ubyte
    fashion-mnist_test.csv
    fashion-mnist_train.csv
    train-labels-idx1-ubyte
    train-images-idx3-ubyte

In [3]:
import pandas as pd

df = pd.read_csv(
    "/kaggle/input/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv"
)

print(df.shape)
df.head()

(50000, 2)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
print(df['sentiment'].value_counts())

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [5]:
df['sentiment'] = df['sentiment'].map({
    'positive': 1,
    'negative': 0
})

df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [6]:
X = df['review']
y = df['sentiment']

print(X.shape)
print(y.shape)

(50000,)
(50000,)

In [7]:
from sklearn.model_selection import train_test_split

X_train_text, X_test_text, y_train_text, y_test_text = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train_text.shape)
print(X_test_text.shape)

(40000,)
(10000,)

In [14]:
# TOKENIZATION
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=10000)

tokenizer.fit_on_texts(X_train_text)

X_train_seq = tokenizer.texts_to_sequences(X_train_text)
X_test_seq = tokenizer.texts_to_sequences(X_test_text)

In [13]:
max_length = 200

X_train_pad = pad_sequences(
    X_train_seq,
    maxlen=max_length
)

X_test_pad = pad_sequences(
    X_test_seq,
    maxlen=max_length
)

print(X_train_pad.shape)
print(X_test_pad.shape)

(40000, 200)
(10000, 200)

In [16]:
# MODEL 4: Dense Neural Network for Sentiment Analysis

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense
from tensorflow.keras import Input

text_model = Sequential([
    Input(shape=(200,)),
    
    Embedding(
        input_dim=10000,
        output_dim=16
    ),

    GlobalAveragePooling1D(),

    Dense(16, activation='relu'),

    Dense(1, activation='sigmoid')
])

text_model.summary()

2026-06-10 07:25:34.167107: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 200, 16)        │       160,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_1      │ (None, 16)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 160,289 (626.13 KB)

 Trainable params: 160,289 (626.13 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
text_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_text = text_model.fit(
    X_train_pad,
    y_train_text,
    epochs=5,
    validation_split=0.2,
    batch_size=32
)

Epoch 1/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7729 - loss: 0.4868 - val_accuracy: 0.8709 - val_loss: 0.3209
Epoch 2/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8852 - loss: 0.2826 - val_accuracy: 0.8770 - val_loss: 0.2933
Epoch 3/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9054 - loss: 0.2362 - val_accuracy: 0.8801 - val_loss: 0.2849
Epoch 4/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9183 - loss: 0.2094 - val_accuracy: 0.8827 - val_loss: 0.2822
Epoch 5/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9272 - loss: 0.1898 - val_accuracy: 0.8845 - val_loss: 0.2821

In [18]:
loss_text, accuracy_text = text_model.evaluate(
    X_test_pad,
    y_test_text
)

print("Dense Text Model Accuracy:", accuracy_text)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8902 - loss: 0.2737
Dense Text Model Accuracy: 0.8902000188827515

In [19]:
# MODEL 5: LSTM

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras import Input

lstm_model = Sequential([
    
    Input(shape=(200,)),
    
    Embedding(
        input_dim=10000,
        output_dim=32
    ),
    
    LSTM(64),
    
    Dense(1, activation='sigmoid')
])

lstm_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 200, 32)        │       320,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 344,897 (1.32 MB)

 Trainable params: 344,897 (1.32 MB)

 Non-trainable params: 0 (0.00 B)

In [20]:
lstm_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_lstm = lstm_model.fit(
    X_train_pad,
    y_train_text,
    epochs=3,
    validation_split=0.2,
    batch_size=64
)

Epoch 1/3
500/500 ━━━━━━━━━━━━━━━━━━━━ 45s 87ms/step - accuracy: 0.7985 - loss: 0.4252 - val_accuracy: 0.8736 - val_loss: 0.3059
Epoch 2/3
500/500 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.9012 - loss: 0.2546 - val_accuracy: 0.8664 - val_loss: 0.3141
Epoch 3/3
500/500 ━━━━━━━━━━━━━━━━━━━━ 42s 84ms/step - accuracy: 0.9230 - loss: 0.2039 - val_accuracy: 0.8789 - val_loss: 0.2998

In [21]:
loss_lstm, accuracy_lstm = lstm_model.evaluate(
    X_test_pad,
    y_test_text
)

print("LSTM Accuracy:", accuracy_lstm)

313/313 ━━━━━━━━━━━━━━━━━━━━ 8s 24ms/step - accuracy: 0.8841 - loss: 0.2855
LSTM Accuracy: 0.8841000199317932

In [22]:
import pandas as pd

comparison_df = pd.DataFrame({
    "Model": [
        "ANN",
        "Deep ANN",
        "CNN",
        "Dense Neural Network",
        "LSTM"
    ],
    
    "Dataset": [
        "Fashion-MNIST",
        "Fashion-MNIST",
        "Fashion-MNIST",
        "IMDB Reviews",
        "IMDB Reviews"
    ],
    
    "Accuracy (%)": [
        86.95,
        86.89,
        91.10,
        89.02,
        88.41
    ]
})

comparison_df

                  Model        Dataset  Accuracy (%)
0                   ANN  Fashion-MNIST         86.95
1              Deep ANN  Fashion-MNIST         86.89
2                   CNN  Fashion-MNIST         91.10
3  Dense Neural Network   IMDB Reviews         89.02
4                  LSTM   IMDB Reviews         88.41